### ISSUE TITLE
#assignTargetDirs reached root

### ISSUE THREAD

**Issue by zbigg** [zbigg/copy-production-deps#6]
Trying to run `copy-production-deps` (v0.1.6) on this repo: https://github.com/yshrsmz/nuxt-serverless-test yields following error

```
copy-production-deps: failed: Error: #assignTargetDirs reached root, report this as bug Error: #assignTargetDirs reached root, report this as bug
    at resolve (/home/zagorski/zz/copy-production-deps/lib/copy-production-deps.js:246:23)
    at getResolved (/home/zagorski/zz/copy-production-deps/lib/copy-production-deps.js:255:17)
    at assignTargetDirs (/home/zagorski/zz/copy-production-deps/lib/copy-production-deps.js:278:9)
    at Object.copyProductionDeps (/home/zagorski/zz/copy-production-deps/lib/copy-production-deps.js:379:28)
    at /home/zagorski/zz/copy-production-deps/lib/cli.js:99:38
    at asyncCommand (/home/zagorski/zz/copy-production-deps/lib/cli.js:32:15)
    at Object.handler (/home/zagorski/zz/copy-production-deps/lib/cli.js:85:18)
    at Object.runCommand (/home/zagorski/zz/copy-production-deps/node_modules/yargs/lib/command.js:240:40)
    at Object.parseArgs [as _parseArgs] (/home/zagorski/zz/copy-production-deps/node_modules/yargs/yargs.js:1164:39)
    at Object.get [as argv] (/home/zagorski/zz/copy-production-deps/node_modules/yargs/yargs.js:1088:21)
```

Followup of #4

**Comment by zbigg** [comment]
This caused by `assignTargetDirs` not supporting namespaced packages like `@nuxt/fuubar`. Current implementation used very naive `dirname(dirname(...)` "method" to advance up into parent `node_modules` while searching for better location for package.
